name: Weekly Blog Posts Generator

on:
  schedule:
    # Run every Monday at 9 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual triggering

jobs:
  generate-blog-posts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Generate blog posts
      run: node scripts/generate-blog-posts.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add src/pages/sk/blog/
        git diff --staged --quiet || git commit -m "🤖 Auto-generate weekly blog posts - $(date +'%Y-%m-%d')"
        git push

